[package]
name = "openssl-llvm-ir"
version = "0.1.0"
edition = "2021"

[dependencies]
llvm-ir = { version = "0.11", features = ["llvm-16"] }
llvm-ir-analysis = { version = "0.4.0", features = ["llvm-16"] }
